vich_uploader:
    db_driver: orm

    mappings:
        information_image:
            uri_prefix: /images/information
            upload_destination: '%kernel.project_dir%/public/images/information'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
